### ISSUE TITLE
Talk Ideas

### ISSUE THREAD

**Issue by MehulATL** [React-IND/React-India-2019-AMA-Kentcdodds#1]
I'd love to give a talk, but have no idea what to talk about.
I know I wanna probably live code something.
any suggestions on topics or how to narrow one down.

**Comment by KirankumarAmbati** [comment]
I have a similar doubt. Thanks for bringing this up.

**Comment by kentcdodds** [comment]
- [My Talks](https://kentcdodds.com/talks)
- [How to Talk to Developers](https://www.youtube.com/watch?v=l9JXH7JPjR4)
