### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by geekysrm** [React-IND/React-India-2019-AMA-Kentcdodds#4]
Where can I find project ideas to implement my knowledge on?
I sometimes find it really hard
Thanks for taking the time :)

**Comment by kentcdodds** [comment]
- [What open source project should I contribute to?](https://kentcdodds.com/blog/what-open-source-project-should-i-contribute-to)
- [Building Production Apps 100% in the browser](https://kentcdodds.com/blog/building-production-apps-100-in-the-browser)
