### ISSUE TITLE
Your opinion on starter kits?

### ISSUE THREAD

**Issue by bmhaskar** [React-IND/React-India-2019-AMA-Kentcdodds#8]
Does it makes sense to have starter kit for React beyond CRA? Specifically for services based org. where multiple teams start working on different projects spending good amount of time in bootstrapping. What would be most common, basic setup that you would include?

**Comment by kentcdodds** [comment]
- [Generators, Boilerplates, and Starter Kits](https://www.briefs.fm/3-minutes-with-kent/25)
- [Tools without config](https://kentcdodds.com/blog/tools-without-config)
- [Concerning toolkits](https://kentcdodds.com/blog/concerning-toolkits)
- [generator-kcd-oss](https://github.com/kentcdodds/generator-kcd-oss)
- [kcd-scripts](https://github.com/kentcdodds/kcd-scripts)
